### PR TITLE
added CODEOWNERS file

### PR DESCRIPTION
**Pull request by thahseen53**
@vanessa-cooper please review

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Comment by thahseen53** [comment]
Review please

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Seems like the `CODEOWNERS` file is missing the right content. Could you fix that and push the changes?

**Review by vanessa-cooper — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Pull request merged**
